FreelancerDemo/Models/WorkRecordViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FreelancerDemo.Models
{
    public class WorkRecordSummaryModel
    {
        [Required(ErrorMessage = "You must select a From date")]
        public DateTime DateFrom { get; set; }
        [Required(ErrorMessage = "You must select a To date")]
        public DateTime DateTo { get; set; }
        public List<WorkRecordSummaryEntry> Entries = new List<WorkRecordSummaryEntry>();
    }

    public class WorkRecordSummaryEntry
    {
        public string Customer;
        public string Project;
        public double Hours;    
    }
}

FreelancerDemo/Controllers/WorkRecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FreelancerDemo.Models;
using WebMatrix.WebData;

namespace FreelancerDemo.Controllers
{
    [Authorize(Roles = "Administrator, Freelancer")]
    public class WorkRecordController : Controller
    {
        private freelancerdbEntities db = new freelancerdbEntities();

        public ActionResult Index()
        {
            List<WorkRecord> records = db.WorkRecord.OrderBy(x => x.Date).ToList();
            var myrecords = new List<WorkRecord>();
            foreach (var record in records)
            {
                if (record.UserId == WebSecurity.CurrentUserId)
                {
                    myrecords.Add(record);
                }    
            }
            return View(myrecords);
        }

        public ActionResult Create()
        {
            ViewBag.UserId = WebSecurity.CurrentUserId;
            ViewBag.WorkTypeId = new SelectList(db.WorkType, "WorkTypeId", "Type");
            ViewBag.ProjectId = new SelectList(db.Project, "ProjectId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(WorkRecord record)
        {
            if (ModelState.IsValid)
            {
                db.WorkRecord.Add(record);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.WorkTypeId = new SelectList(db.WorkType, "WorkTypeId", "Type");
            ViewBag.ProjectId = new SelectList(db.Project, "ProjectId", "Name");
            return View(record);
        }

        public ActionResult Edit(int id = 0)
        {
            WorkRecord workRecord = db.WorkRecord.Find(id);
            ViewBag.WorkTypeId = new SelectList(db.WorkType, "WorkTypeId", "Type");
            ViewBag.ProjectId = new SelectList(db.Project, "ProjectId", "Name");
            if (workRecord == null)
            {
                return HttpNotFound();
            }
            return View(workRecord);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WorkRecord workRecord)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workRecord).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(workRecord);
        }

        public ActionResult Delete(int id = 0)
        {
            WorkRecord record = db.WorkRecord.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkRecord record = db.WorkRecord.Find(id);
            db.WorkRecord.Remove(record);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FreelancerDemo/Views/WorkRecord/Create.cshtml
@model FreelancerDemo.WorkRecord

@{
    ViewBag.Title = "Register Time";
}

<h2>Register Time</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>WorkRecord</legend>
        
        <div class="editor-field">
            @Html.Hidden("UserId")
            @Html.ValidationMessageFor(model => model.UserId)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.WorkTypeId, "WorkType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("WorkTypeId", "Select Type")
            @Html.ValidationMessageFor(model => model.WorkTypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectId, "Project")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ProjectId", "Select Project")
            @Html.ValidationMessageFor(model => model.ProjectId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        
        <input type="text" name="Date" id="Date" class="datefield" />
        @Html.ValidationMessageFor(model => model.Date)

        <div class="editor-label">
            @Html.LabelFor(model => model.Hours)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Hours)
            @Html.ValidationMessageFor(model => model.Hours)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comment)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Comment)
            @Html.ValidationMessageFor(model => model.Comment)
        </div>
       
        <p>
            <button type ="submit">Create</button>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $(".datefield").datepicker({ dateFormat: 'dd-mm-yy' });
        });
    </script>
}

FreelancerDemo/Views/WorkRecord/Delete.cshtml
@model FreelancerDemo.WorkRecord

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>WorkRecord</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.WorkTypeId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WorkTypeId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hours)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hours)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Comment)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comment)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <button type ="submit">Delete</button> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

FreelancerDemo/Views/WorkRecord/Edit.cshtml
@model FreelancerDemo.WorkRecord

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>WorkRecord</legend>

        @Html.HiddenFor(model => model.WorkRecordId)

        <div class="editor-field">
            @Html.Hidden("UserId")
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.WorkTypeId, "WorkType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("WorkTypeId", "Select Type")
            @Html.ValidationMessageFor(model => model.WorkTypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectId, "Project")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ProjectId", "Select Project")
            @Html.ValidationMessageFor(model => model.ProjectId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        
        <input type="text" name="Date" id="Date" class="datefield" />
        @Html.ValidationMessageFor(model => model.Date)

        <div class="editor-label">
            @Html.LabelFor(model => model.Hours)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Hours)
            @Html.ValidationMessageFor(model => model.Hours)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comment)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Comment)
            @Html.ValidationMessageFor(model => model.Comment)
        </div>

        <p>
            <button type ="submit">Save</button>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $(".datefield").datepicker({ dateFormat: 'dd-mm-yy' });
        });
    </script>
}

FreelancerDemo/Views/WorkRecord/Index.cshtml
@model IEnumerable<FreelancerDemo.WorkRecord>

@{
    ViewBag.Title = "Time Registrations";
}

<h2>Time Registrations</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th>
            WorkType
        </th>
        <th>
            Project
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorkType.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Project.Name)
        </td>
        <td>
            @item.Date.ToShortDateString()
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.WorkRecordId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.WorkRecordId })
        </td>
    </tr>
}

</table>
<p>
    <button onclick="location.href='@Url.Action("Create", "WorkRecord")';return false;">Create New</button>
</p>