FreelancerDemo/Controllers/WorkTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreelancerDemo.Controllers
{
    public class WorkTypeController : Controller
    {
        private freelancerdbEntities db = new freelancerdbEntities();

        public ActionResult Index()
        {
            return View(db.WorkType.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WorkType worktype)
        {
            if (ModelState.IsValid)
            {
                db.WorkType.Add(worktype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(worktype);
        }

        public ActionResult Edit(int id = 0)
        {
            WorkType worktype = db.WorkType.Find(id);
            if (worktype == null)
            {
                return HttpNotFound();
            }
            return View(worktype);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WorkType worktype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(worktype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(worktype);
        }

        public ActionResult Delete(int id = 0)
        {
            WorkType worktype = db.WorkType.Find(id);
            if (worktype == null)
            {
                return HttpNotFound();
            }
            return View(worktype);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkType worktype = db.WorkType.Find(id);
            db.WorkType.Remove(worktype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

FreelancerDemo/Views/WorkType/Create.cshtml
@model FreelancerDemo.WorkType

@{
    ViewBag.Title = "Create Worktype";
}

<h2>Create Worktype</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>WorkType</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Type)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Type)
            @Html.ValidationMessageFor(model => model.Type)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <button type ="submit">Create</button>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FreelancerDemo/Views/WorkType/Delete.cshtml
@model FreelancerDemo.WorkType

@{
    ViewBag.Title = "Delete Worktype";
}

<h2>Delete Worktype</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>WorkType</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Type)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Type)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <button type ="submit">Delete</button> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

FreelancerDemo/Views/WorkType/Edit.cshtml
@model FreelancerDemo.WorkType

@{
    ViewBag.Title = "Edit Worktype";
}

<h2>Edit Worktype</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>WorkType</legend>

        @Html.HiddenFor(model => model.WorkTypeId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Type)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Type)
            @Html.ValidationMessageFor(model => model.Type)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <button type ="submit">Save</button>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FreelancerDemo/Views/WorkType/Index.cshtml
@model IEnumerable<FreelancerDemo.WorkType>

@{
    ViewBag.Title = "Worktypes";
}

<h2>Worktypes</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.WorkTypeId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.WorkTypeId })
        </td>
    </tr>
}

</table>

<p>
    <button onclick="location.href='@Url.Action("Create", "WorkType")';return false;">Create New</button>
</p>